### PR TITLE
My most recent work

### PR DESCRIPTION
**Pull request by boney171**
Some Stuff

### CODE REVIEW

**Comment by rsori013** [comment]
for my end i cannot add sets and cannot exit. But it looks good, i installed 
npm install react-native-calendars
npm install react-native-input-spinner

no luck i dont know why

**Comment by VMSandoval25** [comment]
A few notes, don't forget to add pictures or videos to show the work you did. I fixed the merge conflicts so not it should merge without issue.

**Comment by rsori013** [comment]
master victor need some tutorial once again later

**Review by VMSandoval25 — CHANGES_REQUESTED** [review]
When adding the weight of the exercise, please increment by 5 or 10lbs. Incrementing by one is too tedious for the weight. After that please @ me  on discord and I will merge the branch ! (:

**Pull request merged**
