### PR TITLE
Howie/suggested workouts

### PR DESCRIPTION
**Pull request by Howie315**
IMG_6041
IMG_6042
finished the searching and fixed the padding on it as well

### CODE REVIEW

**Comment by Howie315** [comment]
rovin could you check it out for me to see if there's anything wrong with it?

**Comment by rsori013** [comment]
some syntax errrors on my end not sure

**Comment by Howie315** [comment]
> some syntax errrors on my end not sure

could you tell me more in the console whaT THE ERRORS ARE? i need to see them for myself

**Comment by rsori013** [comment]
GGWP

**Pull request merged**
