### PR TITLE
Edit/Delete Exercise Logs Query

### PR DESCRIPTION
**Pull request by boney171**
For this branch, I'm planning to do a few things:

- Remodel the calendar screen, including changing color and making it fits with our app theme. Also changing the styles of 2 buttons: ViewExerciseRecords and RecordAnExercise.
- Build UIs for editing/ deleting functionality for each exercise record in the view exercise logs modal.
- Fix the 0.5-second delay in the viewExerciseRecords modal.
- Implement helper functions to communicate between the UIs that handle modifications of exercise records in the database.

### CODE REVIEW

**Comment by boney171** [comment]
346132744_6179224675517718_6261925420672331878_n

- New look for the calendar page.

**Comment by boney171** [comment]
- Adding color for two buttons on the calendar screen.
- Finished remodeling insert exercise modal.
346124990_630385575306060_7330899268667667082_n
346105119_209415678605728_7489091935471682413_n

**Comment by boney171** [comment]
Finished building UIs for:

- The calendar screen.
- Insert exercise log modal.
- View exercise logs modal.
I will be implementing helper functions to communicate with the database next.
346124990_630385575306060_7330899268667667082_n (1)
346105119_209415678605728_7489091935471682413_n (1)
346147244_254683860470195_8673572453514190998_n

**Comment by boney171** [comment]
- Remodeled the calendar screen, including changing color and making it fits with our app theme. Also changing the styles of 2 buttons: ViewExerciseRecords and RecordAnExercise.
- Built UIs for editing/ deleting functionality for each exercise record in the view exercise logs modal.
- Fixed the 0.5-second delay in the viewExerciseRecords modal.
- Implemented helper functions to communicate between the UIs that handle modifications of exercise records in the database.

https://github.com/CS180-spring/cs180-22-jymbois/assets/97133672/46bed76b-3c77-415a-8dfc-e9463a140639

**Comment by rsori013** [comment]
lgtm

**Pull request merged**
