### PR TITLE
Insert Query Finished.

### PR DESCRIPTION
**Pull request by boney171**

### CODE REVIEW

**Comment by boney171** [comment]
Hi, got nothing, bye, nothing works, bye.

**Comment by boney171** [comment]
[Brainstorming_and_Ideation_1.pdf](https://github.com/CS180-spring/cs180-22-jymbois/files/11394061/Brainstorming_and_Ideation_1.pdf)

**Comment by boney171** [comment]
[Logic_For_Queries_Database.pdf](https://github.com/CS180-spring/cs180-22-jymbois/files/11394063/Logic_For_Queries_Database.pdf)

**Comment by rsori013** [comment]
trying it what matters! thank you for learning backend for us

**Comment by boney171** [comment]
Progress baby 👍

**Comment by boney171** [comment]
Got writeData() and readData() to work, I'll be connecting the UI and the database together

**Comment by boney171** [comment]
Need to implement update() function to write different data into the database without changing pre-existed data.

**Comment by boney171** [comment]
345948919_618532550156759_4270432527523905338_n
346108682_213405531403032_2141925424469653938_n
I built helper functions that communicate between the UI and the database following the logic of the insert queries. You can check out the pictures to see how it works.

**Review by VMSandoval25 — CHANGES_REQUESTED** [review]
A few comments: 
- The user UID is currently static. Lets change that so it is not static anymore. Maybe merging main into this would be helpful since the branch is pretty far behind
- So far you have made great progress!

**Comment by boney171** [comment]
image
Fixed the old version on my branch, changed static Uid to the current user Id.

**Review by VMSandoval25 — APPROVED** [review]

**Comment by VMSandoval25** [comment]
Great work! I think in the future we are going to have to make weight optional for the exercise if they want to do something like cardio. But overall great work!

**Pull request merged**
